
class Config:
    DIGIT_MIN_HEIGHT=15
    DIGIT_MAX_HEIGHT=100
    DIGIT_W_H_MIN_RATIO=.20
    DIGIT_W_H_MAX_RATIO=.60

    DIGIT_RESIZE_HEIGHT=30
    DIGIT_RESIZE_WIDTH=15

    MAX_IMG_SIZE=1920
    CANNY_MIN=150
    CANNY_MAX=200
    HOUGH_PERC_THRESH=0.05
    HOUGH_MIN_THRESH=150
    LEVEL_THRESH=10 #lines between +/- of horizontal are considered horizontal

